### ISSUE TITLE
Rotate prop

### ISSUE THREAD

**Issue by TheJaredWilcurt** [Renovamen/oh-vue-icons#36]
```html
<VIcon
  flip="both"
  rotate="90"
/>
```

You should be able to rotate the icon by 90º, 180º and 270º.

The styling could be handled like so:

```css
.ov-flip-horizontal {
  transform: scale(-1, 1);
}
.ov-rotate-90 {
  transform: rotate(90deg);
}
.ov-flip-horizontal.ov-rotate-90 {
  transform: scale(-1, 1) rotate(90deg);
}
```
Then all the combinations
